FROM dunglas/frankenphp:php8.3-bookworm

WORKDIR /app

RUN install-php-extensions \
    pdo_mysql \
    mbstring \
    curl \
    zip
RUN printf "upload_max_filesize=100M\npost_max_size=110M\nmax_execution_time=180\n" > /usr/local/etc/php/conf.d/uploads.ini


COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . /app/

RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN mkdir -p /app/storage/logs \
    && chmod -R 775 /app/storage

CMD ["sh", "-c", "frankenphp php-server --listen 0.0.0.0:${PORT:-80} --root /app"]