<?php
declare(strict_types=1);

section('Public registration disabled');
$email = Env::get('SEED_USER_EMAIL');
$signup = ['password' => Env::get('SEED_USER_PASSWORD')];
$newUser = Database::fetch('SELECT * FROM users WHERE email = ?', [$email]);
expectStatus('registration endpoint is disabled even with elevated role claims', http('POST', 'auth/register.php', ['name' => 'Injected Admin', 'email' => "inject_$runId@example.test", 'phone' => '9876543210', 'password' => 'StrongPassw0rd!', 'password_confirmation' => 'StrongPassw0rd!', 'role' => 'super_admin', 'role_id' => 1]), 410);
check('disabled registration created no account', Database::value('SELECT 1 FROM users WHERE email = ?', ["inject_$runId@example.test"]) === null);
$publicToken = login('user', $signup['password']);
check('existing seeded user login still works', $publicToken !== null);
expectStatus('user cannot escalate own role', http('PUT', 'users/update.php', ['id' => $newUser['id'], 'role' => 'admin'], $publicToken), 403);

section('Phase 4 — Password reset via SMTP');
$mailbox = Env::get('TEST_MAILBOX_URL');
if (!$mailbox) throw new RuntimeException('Phase 4 mail tests require run-isolated.mjs');
expectStatus('invalid forgot email', http('POST', 'auth/forgot-password.php', ['email' => 'bad']), 422);
$known = http('POST', 'auth/forgot-password.php', ['email' => $email]);
$unknown = http('POST', 'auth/forgot-password.php', ['email' => "missing_$runId@example.test"]);
check('forgot response conceals account existence', $known['status'] === 200 && $known['body'] === $unknown['body']);
$messages = json_decode(file_get_contents($mailbox), true);
$message = end($messages);
preg_match('/#token=([a-f0-9]{64})/', $message['body'] ?? '', $match);
$resetToken = $match[1] ?? '';
check('SMTP delivered actual frontend reset link', strlen($resetToken) === 64 && str_contains($message['body'] ?? '', 'http://localhost:5173/reset-password#token=') && $message['recipient'] === $email);
$resetRow = Database::fetch('SELECT * FROM password_reset_tokens WHERE user_id = ? ORDER BY id DESC LIMIT 1', [$newUser['id']]);
check('only hash stored and 30 minute expiry', $resetRow && $resetRow['token_hash'] === hash('sha256', $resetToken) && strtotime($resetRow['expires_at']) > time());
check('raw token absent from API and audit logs', !str_contains($known['raw'], $resetToken) && !Database::value('SELECT 1 FROM activity_logs WHERE description LIKE ? OR metadata LIKE ?', ["%$resetToken%", "%$resetToken%"]));
$resetBody = ['token' => $resetToken, 'password' => 'NewStrongPass1!', 'password_confirmation' => 'NewStrongPass1!', 'user_id' => 1];
expectStatus('invalid token', http('POST', 'auth/reset-password.php', array_replace($resetBody, ['token' => str_repeat('0',64)])), 422);
expectStatus('missing token', http('POST', 'auth/reset-password.php', array_diff_key($resetBody, ['token' => 1])), 422);
expectStatus('weak reset password', http('POST', 'auth/reset-password.php', array_replace($resetBody, ['password' => 'weak', 'password_confirmation' => 'weak'])), 422);
expectStatus('mismatched reset password', http('POST', 'auth/reset-password.php', array_replace($resetBody, ['password_confirmation' => 'AnotherPass1'])), 422);
Database::execute('UPDATE password_reset_tokens SET expires_at = NOW() - INTERVAL 1 SECOND WHERE id = ?', [$resetRow['id']]);
expectStatus('expired token rejected', http('POST', 'auth/reset-password.php', $resetBody), 422);
Database::execute('UPDATE password_reset_tokens SET expires_at = NOW() + INTERVAL 30 MINUTE WHERE id = ?', [$resetRow['id']]);
$saHash = Database::value('SELECT password_hash FROM users WHERE id = 1');
expectStatus('reset succeeds', http('POST', 'auth/reset-password.php', $resetBody), 200);
check('manipulated user_id cannot reset another user', Database::value('SELECT password_hash FROM users WHERE id = 1') === $saHash);
expectStatus('token cannot be reused', http('POST', 'auth/reset-password.php', $resetBody), 422);
expectStatus('old sessions revoked', http('GET', 'auth/me.php', null, $publicToken), 401);
expectStatus('old password rejected', http('POST', 'auth/login.php', ['login' => $email, 'password' => $signup['password']]), 401);
check('new password accepted', login($email, 'NewStrongPass1!') !== null);
$us = login('user', 'NewStrongPass1!'); // reset correctly revoked the old session
$selfReset = http('POST', 'auth/forgot-password-self.php', [], $us);
$messages = json_decode(file_get_contents($mailbox), true);
check('authenticated password recovery sends only to session account', $selfReset['status'] === 200 && end($messages)['recipient'] === $email);

section('Phase 4 — CRM and follow-up permissions');
$crm = ['record_id' => $draft, 'priority' => 'urgent', 'contact_status' => 'attempted', 'next_action' => 'Arrange a site visit', 'assigned_to' => 3];
expectStatus('owner can update CRM of approved record', http('PUT', 'records/crm.php', $crm + ['approval_status' => 'rejected', 'created_by' => $otherId], $us), 200);
check('CRM cannot mutate approval or ownership', Database::value('SELECT approval_status FROM real_estate_records WHERE id = ?', [$draft]) === 'approved' && (int) Database::value('SELECT created_by FROM real_estate_records WHERE id = ?', [$draft]) === 3);
expectStatus('other user cannot mutate CRM', http('PUT', 'records/crm.php', $crm, $ot), 404);
expectStatus('other admin cannot mutate CRM', http('PUT', 'records/crm.php', $crm, $ad2), 404);
expectStatus('super admin CRM view-only', http('PUT', 'records/crm.php', $crm, $sa), 403);
expectStatus('cannot assign private record outside visibility', http('PUT', 'records/crm.php', array_replace($crm, ['assigned_to' => $otherId]), $ad), 422);
expectStatus('invalid priority', http('PUT', 'records/crm.php', array_replace($crm, ['priority' => 'injected']), $us), 422);
$follow = ['record_id' => $draft, 'assigned_to' => 3, 'due_at' => gmdate('Y-m-d\TH:i:s\Z', time() + 3600), 'type' => 'site_visit', 'notes' => 'Meet at the gate'];
$res = http('POST', 'follow-ups/create.php', $follow, $us);
expectStatus('create follow-up', $res, 201);
$followId = $res['body']['data']['id'];
expectStatus('follow-up invalid date', http('POST', 'follow-ups/create.php', array_replace($follow, ['due_at' => '2026-02-31T12:00:00Z']), $us), 422);
expectStatus('follow-up invalid type', http('POST', 'follow-ups/create.php', array_replace($follow, ['type' => 'hack']), $us), 422);
expectStatus('follow-up invalid notes type', http('POST', 'follow-ups/create.php', array_replace($follow, ['notes' => []]), $us), 422);
expectStatus('other user cannot create follow-up', http('POST', 'follow-ups/create.php', $follow, $ot), 404);
expectStatus('other user cannot complete follow-up', http('PUT', 'follow-ups/update.php', ['id' => $followId, 'status' => 'completed'], $ot), 404);
expectStatus('record-filtered list cannot bypass scope', http('GET', "follow-ups/list.php?record_id=$draft", null, $ot), 404);
$res = http('GET', "follow-ups/list.php?record_id=$draft&per_page=1", null, $us);
check('follow-up list paginated and scoped', $res['status'] === 200 && count($res['body']['data']['items']) === 1 && $res['body']['data']['pagination']['total'] === 1);
check('summary matches database', $res['body']['data']['summary']['pending'] === 1);
expectStatus('super admin reads CRM', http('GET', "follow-ups/list.php?record_id=$draft", null, $sa), 200);
http('GET', 'notifications/list.php', null, $us);
http('GET', 'notifications/list.php', null, $us);
check('follow-up reminder generated once', (int) Database::value("SELECT COUNT(*) FROM notifications WHERE user_id = 3 AND type = 'follow_up.reminder' AND entity_id = ?", [$draft]) === 1);
expectStatus('admin reschedules follow-up', http('PUT', 'follow-ups/update.php', ['id' => $followId, 'status' => 'pending', 'due_at' => gmdate('Y-m-d\TH:i:s\Z', time()+86400*2)], $ad), 200);
expectStatus('owner completes follow-up', http('PUT', 'follow-ups/update.php', ['id' => $followId, 'status' => 'completed'], $us), 200);
check('completion time stored', Database::value('SELECT completed_at FROM follow_ups WHERE id = ?', [$followId]) !== null);
expectStatus('owner cancels follow-up', http('PUT', 'follow-ups/update.php', ['id' => $followId, 'status' => 'cancelled'], $us), 200);
expectStatus('reopen follow-up', http('PUT', 'follow-ups/update.php', ['id' => $followId, 'status' => 'pending'], $us), 200);

section('Phase 4 — Interaction timeline and search');
foreach (['note', ...CRM::TYPES] as $type) expectStatus("record $type interaction", http('POST', 'activities/create.php', ['record_id' => $draft, 'type' => $type, 'description' => "Test $type interaction"], $us), 201);
check('last contacted persisted', Database::value('SELECT last_contacted_at FROM real_estate_records WHERE id = ?', [$draft]) !== null);
expectStatus('other user cannot add notes', http('POST', 'activities/create.php', ['record_id' => $draft, 'type' => 'note', 'description' => 'Private note'], $ot), 404);
expectStatus('other user cannot read timeline', http('GET', "activities/list.php?record_id=$draft", null, $ot), 404);
$res = http('GET', "activities/list.php?record_id=$draft&per_page=2", null, $us);
check('timeline contains paginated real audit events', count($res['body']['data']['items']) === 2 && $res['body']['data']['pagination']['total'] >= 7);
check('priority filter', in_array($draft, $ids($us, 'priority=urgent'), true) && !in_array($draft, $ids($us, 'priority=low'), true));
check('assignment filter', in_array($draft, $ids($ad, 'assigned_to=3'), true));
check('follow-up filter', in_array($draft, $ids($ad, 'follow_up_status=pending'), true));
Database::execute('UPDATE parties SET email = ? WHERE id = (SELECT party_id FROM real_estate_records WHERE id = ?)', ["party_$runId@example.test", $draft]);
check('search by party email', in_array($draft, $ids($us, 'search=' . urlencode("party_$runId@example.test")), true));
check('search by status', in_array($draft, $ids($us, 'search=approved'), true));
expectStatus('sorting SQL injection rejected', http('GET', 'records/list.php?sort=DROP%20TABLE%20users', null, $us), 422);
expectStatus('priority sorting supported', http('GET', 'records/list.php?sort=priority', null, $us), 200);
foreach (['follow-ups/list.php','activities/list.php?record_id=' . $draft] as $endpoint) expectStatus('CRM requires authentication', http('GET', $endpoint), 401);

section('Phase 4 — Rate limiting');
for ($i = 0; $i < 10; $i++) http('POST', 'auth/forgot-password.php', ['email' => "missing_$runId@example.test"]);
expectStatus('forgot requests throttled', http('POST', 'auth/forgot-password.php', ['email' => $email]), 429);
